[application]

name = "Zomatree-live"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Zomatree.live"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
