on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: wasm32-unknown-unknown
            default: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - run: cargo install --git https://github.com/dioxuslabs/cli
      - run: dioxus build --release
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 07d4f206f79a6e88398191e198c00f0a
          projectName: zomatree
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
